-- Materialized View: "WADE_R"."CATALOG_SUMMARY_MV"

-- DROP MATERIALIZED VIEW "WADE_R"."CATALOG_SUMMARY_MV";

CREATE MATERIALIZED VIEW "WADE_R"."CATALOG_SUMMARY_MV" AS 
 SELECT "CATALOG_SUMMARY"."ORGANIZATION_ID",
    "CATALOG_SUMMARY"."REPORT_ID",
    "CATALOG_SUMMARY"."DATACATEGORY",
    "CATALOG_SUMMARY"."DATATYPE",
    "CATALOG_SUMMARY"."STATE",
    "CATALOG_SUMMARY"."REPORT_UNIT_ID",
    "CATALOG_SUMMARY"."COUNTY_FIPS",
    "CATALOG_SUMMARY"."HUC",
    "CATALOG_SUMMARY"."NUMOFALLOCATIONS"
   FROM "WADE_R"."CATALOG_SUMMARY"
WITH NO DATA;

ALTER TABLE "WADE_R"."CATALOG_SUMMARY_MV"
  OWNER TO admin;
GRANT ALL ON TABLE "WADE_R"."CATALOG_SUMMARY_MV" TO admin;
GRANT SELECT ON TABLE "WADE_R"."CATALOG_SUMMARY_MV" TO "WADE_APP";
GRANT ALL ON TABLE "WADE_R"."CATALOG_SUMMARY_MV" TO "WADE_ADMIN";
