-- Materialized View: "WADE_R"."DETAIL_LOCATION_MV"

-- DROP MATERIALIZED VIEW "WADE_R"."DETAIL_LOCATION_MV";

CREATE MATERIALIZED VIEW "WADE_R"."DETAIL_LOCATION_MV" AS 
 SELECT "DETAIL_LOCATION"."ORGANIZATION_ID",
    "DETAIL_LOCATION"."REPORT_ID",
    "DETAIL_LOCATION"."ALLOCATION_ID",
    "DETAIL_LOCATION"."DATACATEGORY",
    "DETAIL_LOCATION"."DATATYPE",
    "DETAIL_LOCATION"."STATE",
    "DETAIL_LOCATION"."REPORTING_UNIT_ID",
    "DETAIL_LOCATION"."COUNTY_FIPS",
    "DETAIL_LOCATION"."HUC"
   FROM "WADE_R"."DETAIL_LOCATION"
WITH NO DATA;

ALTER TABLE "WADE_R"."DETAIL_LOCATION_MV"
  OWNER TO admin;
GRANT ALL ON TABLE "WADE_R"."DETAIL_LOCATION_MV" TO admin;
GRANT SELECT ON TABLE "WADE_R"."DETAIL_LOCATION_MV" TO "WADE_APP";
GRANT ALL ON TABLE "WADE_R"."DETAIL_LOCATION_MV" TO "WADE_ADMIN";
