-- View: "WADE_R"."DETAIL_LOCATION"

-- DROP VIEW "WADE_R"."DETAIL_LOCATION";

CREATE OR REPLACE VIEW "WADE_R"."DETAIL_LOCATION" AS 
 SELECT DISTINCT a."ORGANIZATION_ID",
    a."REPORT_ID",
    a."ALLOCATION_ID",
    'DETAIL'::text AS "DATACATEGORY",
    'ALLOCATION'::text AS "DATATYPE",
    b."STATE",
    b."REPORTING_UNIT_ID",
    b."COUNTY_FIPS",
    b."HUC"
   FROM "WADE"."DETAIL_ALLOCATION" a
     JOIN "WADE"."D_ALLOCATION_LOCATION" b ON a."ORGANIZATION_ID"::text = b."ORGANIZATION_ID"::text AND a."REPORT_ID"::text = b."REPORT_ID"::text AND a."ALLOCATION_ID"::text = b."ALLOCATION_ID"::text
  WHERE b."REPORTING_UNIT_ID" IS NOT NULL OR b."COUNTY_FIPS" IS NOT NULL OR b."HUC" IS NOT NULL
UNION
 SELECT DISTINCT "DETAIL_DIVERSION"."ORGANIZATION_ID",
    "DETAIL_DIVERSION"."REPORT_ID",
    "DETAIL_DIVERSION"."ALLOCATION_ID",
    'DETAIL'::text AS "DATACATEGORY",
    'DIVERSION'::text AS "DATATYPE",
    "DETAIL_DIVERSION"."STATE",
    "DETAIL_DIVERSION"."REPORTING_UNIT_ID",
    "DETAIL_DIVERSION"."COUNTY_FIPS",
    "DETAIL_DIVERSION"."HUC"
   FROM "WADE"."DETAIL_DIVERSION"
  WHERE "DETAIL_DIVERSION"."REPORTING_UNIT_ID" IS NOT NULL OR "DETAIL_DIVERSION"."COUNTY_FIPS" IS NOT NULL OR "DETAIL_DIVERSION"."HUC" IS NOT NULL
UNION
 SELECT DISTINCT a."ORGANIZATION_ID",
    a."REPORT_ID",
    a."ALLOCATION_ID",
    'DETAIL'::text AS "DATACATEGORY",
    'USE'::text AS "DATATYPE",
    b."STATE",
    b."REPORTING_UNIT_ID",
    b."COUNTY_FIPS",
    b."HUC"
   FROM "WADE"."DETAIL_USE" a
     JOIN "WADE"."D_USE_LOCATION" b ON a."ORGANIZATION_ID"::text = b."ORGANIZATION_ID"::text AND a."REPORT_ID"::text = b."REPORT_ID"::text AND a."ALLOCATION_ID"::text = b."ALLOCATION_ID"::text
  WHERE b."REPORTING_UNIT_ID" IS NOT NULL OR b."COUNTY_FIPS" IS NOT NULL OR b."HUC" IS NOT NULL
UNION
 SELECT DISTINCT "DETAIL_RETURN_FLOW"."ORGANIZATION_ID",
    "DETAIL_RETURN_FLOW"."REPORT_ID",
    "DETAIL_RETURN_FLOW"."ALLOCATION_ID",
    'DETAIL'::text AS "DATACATEGORY",
    'RETURN'::text AS "DATATYPE",
    "DETAIL_RETURN_FLOW"."STATE",
    "DETAIL_RETURN_FLOW"."REPORTING_UNIT_ID",
    "DETAIL_RETURN_FLOW"."COUNTY_FIPS",
    "DETAIL_RETURN_FLOW"."HUC"
   FROM "WADE"."DETAIL_RETURN_FLOW"
  WHERE "DETAIL_RETURN_FLOW"."REPORTING_UNIT_ID" IS NOT NULL OR "DETAIL_RETURN_FLOW"."COUNTY_FIPS" IS NOT NULL OR "DETAIL_RETURN_FLOW"."HUC" IS NOT NULL;

ALTER TABLE "WADE_R"."DETAIL_LOCATION"
  OWNER TO "WADE";
COMMENT ON VIEW "WADE_R"."DETAIL_LOCATION"
  IS 'View to provide the locations for each allocation.';
