-- View: "WADE_R"."FULL_CATALOG"

-- DROP VIEW "WADE_R"."FULL_CATALOG";

CREATE OR REPLACE VIEW "WADE_R"."FULL_CATALOG" AS 
 SELECT "SUMMARY_LOCATION"."ORGANIZATION_ID",
    "SUMMARY_LOCATION"."REPORT_ID",
    "SUMMARY_LOCATION"."ALLOCATION_ID",
    "SUMMARY_LOCATION"."DATACATEGORY",
    "SUMMARY_LOCATION"."DATATYPE",
    "SUMMARY_LOCATION"."STATE",
    "SUMMARY_LOCATION"."REPORT_UNIT_ID",
    "SUMMARY_LOCATION"."COUNTY_FIPS",
    "SUMMARY_LOCATION"."HUC"
   FROM "WADE_R"."SUMMARY_LOCATION"
UNION
 SELECT "DETAIL_LOCATION"."ORGANIZATION_ID",
    "DETAIL_LOCATION"."REPORT_ID",
    "DETAIL_LOCATION"."ALLOCATION_ID",
    "DETAIL_LOCATION"."DATACATEGORY",
    "DETAIL_LOCATION"."DATATYPE",
    "DETAIL_LOCATION"."STATE",
    "DETAIL_LOCATION"."REPORTING_UNIT_ID" AS "REPORT_UNIT_ID",
    "DETAIL_LOCATION"."COUNTY_FIPS",
    "DETAIL_LOCATION"."HUC"
   FROM "WADE_R"."DETAIL_LOCATION";

ALTER TABLE "WADE_R"."FULL_CATALOG"
  OWNER TO "WADE";
COMMENT ON VIEW "WADE_R"."FULL_CATALOG"
  IS 'View to provide full Catalog for catalog service.';
