-- Materialized View: "WADE_R"."SUMMARY_LOCATION_MV"

-- DROP MATERIALIZED VIEW "WADE_R"."SUMMARY_LOCATION_MV";

CREATE MATERIALIZED VIEW "WADE_R"."SUMMARY_LOCATION_MV" AS 
 SELECT "SUMMARY_LOCATION"."ORGANIZATION_ID",
    "SUMMARY_LOCATION"."REPORT_ID",
    "SUMMARY_LOCATION"."ALLOCATION_ID",
    "SUMMARY_LOCATION"."DATACATEGORY",
    "SUMMARY_LOCATION"."DATATYPE",
    "SUMMARY_LOCATION"."STATE",
    "SUMMARY_LOCATION"."REPORT_UNIT_ID",
    "SUMMARY_LOCATION"."COUNTY_FIPS",
    "SUMMARY_LOCATION"."HUC"
   FROM "WADE_R"."SUMMARY_LOCATION"
WITH NO DATA;

ALTER TABLE "WADE_R"."SUMMARY_LOCATION_MV"
  OWNER TO admin;
GRANT ALL ON TABLE "WADE_R"."SUMMARY_LOCATION_MV" TO admin;
GRANT SELECT ON TABLE "WADE_R"."SUMMARY_LOCATION_MV" TO "WADE_APP";
GRANT ALL ON TABLE "WADE_R"."SUMMARY_LOCATION_MV" TO "WADE_ADMIN";
