-- View: "WADE_R"."SUMMARY_LOCATION"

-- DROP VIEW "WADE_R"."SUMMARY_LOCATION";

CREATE OR REPLACE VIEW "WADE_R"."SUMMARY_LOCATION" AS 
 SELECT DISTINCT a."ORGANIZATION_ID",
    a."REPORT_ID",
    '0'::text AS "ALLOCATION_ID",
    'SUMMARY'::text AS "DATACATEGORY",
    'ALLOCATION'::text AS "DATATYPE",
    b."STATE",
    b."REPORT_UNIT_ID",
    b."COUNTY_FIPS",
    b."HUC"
   FROM "WADE"."SUMMARY_ALLOCATION" a
     JOIN "WADE"."REPORTING_UNIT" b ON a."REPORT_UNIT_ID"::text = b."REPORT_UNIT_ID"::text AND a."REPORT_ID"::text = b."REPORT_ID"::text AND a."ORGANIZATION_ID"::text = b."ORGANIZATION_ID"::text
UNION
 SELECT DISTINCT a."ORGANIZATION_ID",
    a."REPORT_ID",
    '0'::text AS "ALLOCATION_ID",
    'SUMMARY'::text AS "DATACATEGORY",
    'AVAILABILITY'::text AS "DATATYPE",
    b."STATE",
    b."REPORT_UNIT_ID",
    b."COUNTY_FIPS",
    b."HUC"
   FROM "WADE"."SUMMARY_AVAILABILITY" a
     JOIN "WADE"."REPORTING_UNIT" b ON a."REPORT_UNIT_ID"::text = b."REPORT_UNIT_ID"::text AND a."REPORT_ID"::text = b."REPORT_ID"::text AND a."ORGANIZATION_ID"::text = b."ORGANIZATION_ID"::text
UNION
 SELECT DISTINCT a."ORGANIZATION_ID",
    a."REPORT_ID",
    '0'::text AS "ALLOCATION_ID",
    'SUMMARY'::text AS "DATACATEGORY",
    'REGULATORY'::text AS "DATATYPE",
    b."STATE",
    b."REPORT_UNIT_ID",
    b."COUNTY_FIPS",
    b."HUC"
   FROM "WADE"."SUMMARY_REGULATORY" a
     JOIN "WADE"."REPORTING_UNIT" b ON a."REPORT_UNIT_ID"::text = b."REPORT_UNIT_ID"::text AND a."REPORT_ID"::text = b."REPORT_ID"::text AND a."ORGANIZATION_ID"::text = b."ORGANIZATION_ID"::text
UNION
 SELECT DISTINCT a."ORGANIZATION_ID",
    a."REPORT_ID",
    '0'::text AS "ALLOCATION_ID",
    'SUMMARY'::text AS "DATACATEGORY",
    'USE'::text AS "DATATYPE",
    b."STATE",
    b."REPORT_UNIT_ID",
    b."COUNTY_FIPS",
    b."HUC"
   FROM "WADE"."SUMMARY_USE" a
     JOIN "WADE"."REPORTING_UNIT" b ON a."REPORT_UNIT_ID"::text = b."REPORT_UNIT_ID"::text AND a."REPORT_ID"::text = b."REPORT_ID"::text AND a."ORGANIZATION_ID"::text = b."ORGANIZATION_ID"::text
UNION
 SELECT DISTINCT a."ORGANIZATION_ID",
    a."REPORT_ID",
    '0'::text AS "ALLOCATION_ID",
    'SUMMARY'::text AS "DATACATEGORY",
    'SUPPLY'::text AS "DATATYPE",
    b."STATE",
    b."REPORT_UNIT_ID",
    b."COUNTY_FIPS",
    b."HUC"
   FROM "WADE"."SUMMARY_WATER_SUPPLY" a
     JOIN "WADE"."REPORTING_UNIT" b ON a."REPORT_UNIT_ID"::text = b."REPORT_UNIT_ID"::text AND a."REPORT_ID"::text = b."REPORT_ID"::text AND a."ORGANIZATION_ID"::text = b."ORGANIZATION_ID"::text;

ALTER TABLE "WADE_R"."SUMMARY_LOCATION"
  OWNER TO "WADE";
COMMENT ON VIEW "WADE_R"."SUMMARY_LOCATION"
  IS 'View to provide the locations for the summary data.';
