-- Table: "WADE"."D_CONSUMPTIVE_USE"

-- DROP TABLE "WADE"."D_CONSUMPTIVE_USE";

CREATE TABLE "WADE"."D_CONSUMPTIVE_USE"
(
  "ORGANIZATION_ID" character varying(10) NOT NULL, -- A unique identifier assigned to the organziation.
  "REPORT_ID" character varying(35) NOT NULL, -- A unique identifier assigned to the report by the reporting organziation.
  "ALLOCATION_ID" character varying(60) NOT NULL, -- Unique identifier for the allocation.
  "WATER_USER_ID" character varying(50) NOT NULL, -- A unique identifier for the water user.
  "BENEFICIAL_USE_ID" numeric(18,0) NOT NULL, -- A unique identifier identifying the beneficial use.
  "SOURCE_TYPE" numeric(18,0),
  "FRESH_SALINE_IND" numeric(18,0),
  "SOURCE_NAME" character varying(60),
  CONSTRAINT "PK_D_CONSUMPTIVE_USE" PRIMARY KEY ("ORGANIZATION_ID", "REPORT_ID", "ALLOCATION_ID", "WATER_USER_ID", "BENEFICIAL_USE_ID"),
  CONSTRAINT "FK_D_CONSUMPTIVE_USE-DETAIL_USE" FOREIGN KEY ("ORGANIZATION_ID", "REPORT_ID", "ALLOCATION_ID", "WATER_USER_ID")
      REFERENCES "WADE"."DETAIL_USE" ("ORGANIZATION_ID", "REPORT_ID", "ALLOCATION_ID", "WATER_USER_ID") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "FK_D_CONSUMPTIVE_USE-LU_BENEFICIAL_USE" FOREIGN KEY ("BENEFICIAL_USE_ID")
      REFERENCES "WADE"."LU_BENEFICIAL_USE" ("LU_SEQ_NO") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "FK_D_CONSUMPTIVE_USE-LU_FRESH_SALINE_INDICATOR" FOREIGN KEY ("FRESH_SALINE_IND")
      REFERENCES "WADE"."LU_FRESH_SALINE_INDICATOR" ("LU_SEQ_NO") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "FK_D_CONSUMPTIVE_USE-LU_SOURCE_TYPE" FOREIGN KEY ("SOURCE_TYPE")
      REFERENCES "WADE"."LU_SOURCE_TYPE" ("LU_SEQ_NO") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE "WADE"."D_CONSUMPTIVE_USE"
  OWNER TO "WADE";
COMMENT ON TABLE "WADE"."D_CONSUMPTIVE_USE"
  IS 'The actual ammount of water used at this location for the reporting period.';
COMMENT ON COLUMN "WADE"."D_CONSUMPTIVE_USE"."ORGANIZATION_ID" IS ' A unique identifier assigned to the organziation.';
COMMENT ON COLUMN "WADE"."D_CONSUMPTIVE_USE"."REPORT_ID" IS 'A unique identifier assigned to the report by the reporting organziation.';
COMMENT ON COLUMN "WADE"."D_CONSUMPTIVE_USE"."ALLOCATION_ID" IS 'Unique identifier for the allocation.';
COMMENT ON COLUMN "WADE"."D_CONSUMPTIVE_USE"."WATER_USER_ID" IS 'A unique identifier for the water user.';
COMMENT ON COLUMN "WADE"."D_CONSUMPTIVE_USE"."BENEFICIAL_USE_ID" IS 'A unique identifier identifying the beneficial use.';


-- Index: "WADE"."FKI_D_CONSUMPTIVE_USE-DETAIL_USE"

-- DROP INDEX "WADE"."FKI_D_CONSUMPTIVE_USE-DETAIL_USE";

CREATE INDEX "FKI_D_CONSUMPTIVE_USE-DETAIL_USE"
  ON "WADE"."D_CONSUMPTIVE_USE"
  USING btree
  ("ORGANIZATION_ID" COLLATE pg_catalog."default", "REPORT_ID" COLLATE pg_catalog."default", "ALLOCATION_ID" COLLATE pg_catalog."default", "WATER_USER_ID" COLLATE pg_catalog."default");

-- Index: "WADE"."FKI_D_CONSUMPTIVE_USE-LU_BENEFICIAL_USE"

-- DROP INDEX "WADE"."FKI_D_CONSUMPTIVE_USE-LU_BENEFICIAL_USE";

CREATE INDEX "FKI_D_CONSUMPTIVE_USE-LU_BENEFICIAL_USE"
  ON "WADE"."D_CONSUMPTIVE_USE"
  USING btree
  ("BENEFICIAL_USE_ID");

-- Index: "WADE"."FKI_D_CONSUMPTIVE_USE-LU_FRESH_SALINE_INDICATOR"

-- DROP INDEX "WADE"."FKI_D_CONSUMPTIVE_USE-LU_FRESH_SALINE_INDICATOR";

CREATE INDEX "FKI_D_CONSUMPTIVE_USE-LU_FRESH_SALINE_INDICATOR"
  ON "WADE"."D_CONSUMPTIVE_USE"
  USING btree
  ("FRESH_SALINE_IND");

-- Index: "WADE"."FKI_D_CONSUMPTIVE_USE-LU_SOURCE_TYPE"

-- DROP INDEX "WADE"."FKI_D_CONSUMPTIVE_USE-LU_SOURCE_TYPE";

CREATE INDEX "FKI_D_CONSUMPTIVE_USE-LU_SOURCE_TYPE"
  ON "WADE"."D_CONSUMPTIVE_USE"
  USING btree
  ("SOURCE_TYPE");

