-- Table: "WADE"."D_DIVERSION_FLOW"

-- DROP TABLE "WADE"."D_DIVERSION_FLOW";

CREATE TABLE "WADE"."D_DIVERSION_FLOW"
(
  "ORGANIZATION_ID" character varying(10) NOT NULL, -- Unique identifier for the organization.
  "REPORT_ID" character varying(35) NOT NULL, -- A unique identifier for the report assigned by the reporting organization.
  "ALLOCATION_ID" character varying(60) NOT NULL,
  "DIVERSION_ID" character varying(35) NOT NULL,
  "DETAIL_SEQ_NO" numeric(18,0) NOT NULL,
  "AMOUNT_VOLUME" numeric(18,3),
  "UNIT_VOLUME" numeric(18,0),
  "AMOUNT_RATE" numeric(18,3),
  "UNIT_RATE" numeric(18,0),
  "SOURCE_TYPE" numeric(18,0),
  "FRESH_SALINE_IND" numeric(18,0),
  "DIVERSION_START" character(5),
  "DIVERSION_END" character varying(5),
  "SOURCE_NAME" character varying(60),
  CONSTRAINT "PK_D_DIVERSION_FLOW" PRIMARY KEY ("ORGANIZATION_ID", "REPORT_ID", "ALLOCATION_ID", "DIVERSION_ID", "DETAIL_SEQ_NO"),
  CONSTRAINT "FK_D_DIVERSION_FLOW-DETAIL_DIVERSION" FOREIGN KEY ("ORGANIZATION_ID", "REPORT_ID", "ALLOCATION_ID", "DIVERSION_ID")
      REFERENCES "WADE"."DETAIL_DIVERSION" ("ORGANIZATION_ID", "REPORT_ID", "ALLOCATION_ID", "DIVERSION_ID") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "FK_D_DIVERSION_FLOW-LU_FRESH_SALINE_INDICATOR" FOREIGN KEY ("FRESH_SALINE_IND")
      REFERENCES "WADE"."LU_FRESH_SALINE_INDICATOR" ("LU_SEQ_NO") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "FK_D_DIVERSION_FLOW-LU_SOURCE_TYPE" FOREIGN KEY ("SOURCE_TYPE")
      REFERENCES "WADE"."LU_SOURCE_TYPE" ("LU_SEQ_NO") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "FK_D_DIVERSION_FLOW-LU_UNITS" FOREIGN KEY ("UNIT_VOLUME")
      REFERENCES "WADE"."LU_UNITS" ("LU_SEQ_NO") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "FK_D_DIVERSION_FLOW-LU_UNITS1" FOREIGN KEY ("UNIT_RATE")
      REFERENCES "WADE"."LU_UNITS" ("LU_SEQ_NO") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE "WADE"."D_DIVERSION_FLOW"
  OWNER TO "WADE";
COMMENT ON TABLE "WADE"."D_DIVERSION_FLOW"
  IS 'The amount of water allocated for this diversion.';
COMMENT ON COLUMN "WADE"."D_DIVERSION_FLOW"."ORGANIZATION_ID" IS 'Unique identifier for the organization.';
COMMENT ON COLUMN "WADE"."D_DIVERSION_FLOW"."REPORT_ID" IS 'A unique identifier for the report assigned by the reporting organization.';


-- Index: "WADE"."FKI_D_DIVERSION_FLOW-DETAIL_DIVERSION"

-- DROP INDEX "WADE"."FKI_D_DIVERSION_FLOW-DETAIL_DIVERSION";

CREATE INDEX "FKI_D_DIVERSION_FLOW-DETAIL_DIVERSION"
  ON "WADE"."D_DIVERSION_FLOW"
  USING btree
  ("ORGANIZATION_ID" COLLATE pg_catalog."default", "REPORT_ID" COLLATE pg_catalog."default", "ALLOCATION_ID" COLLATE pg_catalog."default", "DIVERSION_ID" COLLATE pg_catalog."default");

-- Index: "WADE"."FKI_D_DIVERSION_FLOW-LU_FRESH_SALINE_INDICATOR"

-- DROP INDEX "WADE"."FKI_D_DIVERSION_FLOW-LU_FRESH_SALINE_INDICATOR";

CREATE INDEX "FKI_D_DIVERSION_FLOW-LU_FRESH_SALINE_INDICATOR"
  ON "WADE"."D_DIVERSION_FLOW"
  USING btree
  ("FRESH_SALINE_IND");

-- Index: "WADE"."FKI_D_DIVERSION_FLOW-LU_SOURCE_TYPE"

-- DROP INDEX "WADE"."FKI_D_DIVERSION_FLOW-LU_SOURCE_TYPE";

CREATE INDEX "FKI_D_DIVERSION_FLOW-LU_SOURCE_TYPE"
  ON "WADE"."D_DIVERSION_FLOW"
  USING btree
  ("SOURCE_TYPE");

-- Index: "WADE"."FKI_D_DIVERSION_FLOW-LU_UNITS"

-- DROP INDEX "WADE"."FKI_D_DIVERSION_FLOW-LU_UNITS";

CREATE INDEX "FKI_D_DIVERSION_FLOW-LU_UNITS"
  ON "WADE"."D_DIVERSION_FLOW"
  USING btree
  ("UNIT_VOLUME");

-- Index: "WADE"."FKI_D_DIVERSION_FLOW-LU_UNITS1"

-- DROP INDEX "WADE"."FKI_D_DIVERSION_FLOW-LU_UNITS1";

CREATE INDEX "FKI_D_DIVERSION_FLOW-LU_UNITS1"
  ON "WADE"."D_DIVERSION_FLOW"
  USING btree
  ("UNIT_RATE");

