-- Table: "WADE"."SUMMARY_AVAILABILITY"

-- DROP TABLE "WADE"."SUMMARY_AVAILABILITY";

CREATE TABLE "WADE"."SUMMARY_AVAILABILITY"
(
  "ORGANIZATION_ID" character varying(10) NOT NULL, -- unique identifier for the organization.
  "REPORT_ID" character varying(35) NOT NULL, -- A unique identifier assigned to the report by the reporting organization.
  "REPORT_UNIT_ID" character varying(35) NOT NULL, -- A unique identifier assigned to the reporting unit by the reporting organization.
  "SUMMARY_SEQ" numeric(18,0) NOT NULL, -- Unique numeric key for summary.
  "AVAILABILITY_TYPE" character varying(50) NOT NULL, -- The type of water available.
  "FRESH_SALINE_IND" numeric(18,0) NOT NULL, -- Indicates whether the source is fresh water, saline water, or represents the total of both.
  "SOURCE_TYPE" numeric(18,0) NOT NULL,
  "WFS_FEATURE_REF" character varying(35),
  CONSTRAINT "PK_SUMMARY_AVAILABILITY" PRIMARY KEY ("ORGANIZATION_ID", "REPORT_ID", "REPORT_UNIT_ID", "SUMMARY_SEQ"),
  CONSTRAINT "FK_SUMMARY_AVAILABILITY-LU_FRESH_SALINE_INDICATOR" FOREIGN KEY ("FRESH_SALINE_IND")
      REFERENCES "WADE"."LU_FRESH_SALINE_INDICATOR" ("LU_SEQ_NO") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "FK_SUMMARY_AVAILABILITY-LU_SOURCE_TYPE" FOREIGN KEY ("SOURCE_TYPE")
      REFERENCES "WADE"."LU_SOURCE_TYPE" ("LU_SEQ_NO") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "FK_SUMMARY_AVAILABILITY-REPORTING_UNIT" FOREIGN KEY ("ORGANIZATION_ID", "REPORT_ID", "REPORT_UNIT_ID")
      REFERENCES "WADE"."REPORTING_UNIT" ("ORGANIZATION_ID", "REPORT_ID", "REPORT_UNIT_ID") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE "WADE"."SUMMARY_AVAILABILITY"
  OWNER TO "WADE";
COMMENT ON TABLE "WADE"."SUMMARY_AVAILABILITY"
  IS 'Summary of water availability within the reporting unit.';
COMMENT ON COLUMN "WADE"."SUMMARY_AVAILABILITY"."ORGANIZATION_ID" IS 'unique identifier for the organization.';
COMMENT ON COLUMN "WADE"."SUMMARY_AVAILABILITY"."REPORT_ID" IS 'A unique identifier assigned to the report by the reporting organization.';
COMMENT ON COLUMN "WADE"."SUMMARY_AVAILABILITY"."REPORT_UNIT_ID" IS 'A unique identifier assigned to the reporting unit by the reporting organization.';
COMMENT ON COLUMN "WADE"."SUMMARY_AVAILABILITY"."SUMMARY_SEQ" IS 'Unique numeric key for summary.';
COMMENT ON COLUMN "WADE"."SUMMARY_AVAILABILITY"."AVAILABILITY_TYPE" IS 'The type of water available.';
COMMENT ON COLUMN "WADE"."SUMMARY_AVAILABILITY"."FRESH_SALINE_IND" IS 'Indicates whether the source is fresh water, saline water, or represents the total of both.';


-- Index: "WADE"."FKI_SUMMARY_AVAILABILITY-LU_FRESH_SALINE_INDICATOR"

-- DROP INDEX "WADE"."FKI_SUMMARY_AVAILABILITY-LU_FRESH_SALINE_INDICATOR";

CREATE INDEX "FKI_SUMMARY_AVAILABILITY-LU_FRESH_SALINE_INDICATOR"
  ON "WADE"."SUMMARY_AVAILABILITY"
  USING btree
  ("FRESH_SALINE_IND");

-- Index: "WADE"."FKI_SUMMARY_AVAILABILITY-LU_SOURCE_TYPE"

-- DROP INDEX "WADE"."FKI_SUMMARY_AVAILABILITY-LU_SOURCE_TYPE";

CREATE INDEX "FKI_SUMMARY_AVAILABILITY-LU_SOURCE_TYPE"
  ON "WADE"."SUMMARY_AVAILABILITY"
  USING btree
  ("SOURCE_TYPE");

-- Index: "WADE"."FKI_SUMMARY_AVAILABILITY-REPORTING_UNIT"

-- DROP INDEX "WADE"."FKI_SUMMARY_AVAILABILITY-REPORTING_UNIT";

CREATE INDEX "FKI_SUMMARY_AVAILABILITY-REPORTING_UNIT"
  ON "WADE"."SUMMARY_AVAILABILITY"
  USING btree
  ("ORGANIZATION_ID" COLLATE pg_catalog."default", "REPORT_ID" COLLATE pg_catalog."default", "REPORT_UNIT_ID" COLLATE pg_catalog."default");

