-- Table: "WADE"."SUMMARY_ALLOCATION"

-- DROP TABLE "WADE"."SUMMARY_ALLOCATION";

CREATE TABLE "WADE"."SUMMARY_ALLOCATION"
(
  "ORGANIZATION_ID" character varying(10) NOT NULL, -- unique identifier assigned to the organization.
  "REPORT_ID" character varying(35) NOT NULL, -- A unique identifier assigned to the report by the reporting organization.
  "REPORT_UNIT_ID" character varying(35) NOT NULL, -- A unique identifier assigned to the reporting unit by the reporting organization.
  "SUMMARY_SEQ" numeric(18,0) NOT NULL, -- Unique sequence number for the summary.
  "BENEFICIAL_USE_ID" numeric(18,0) NOT NULL, -- Unique identifier for the beneficial use.
  "AMOUNT" numeric(18,3) NOT NULL,
  "FRESH_SALINE_IND" numeric(18,0) NOT NULL,
  "SOURCE_TYPE" numeric(18,0) NOT NULL,
  "POWER_GENERATED" numeric(18,3),
  "POPULATION_SERVED" numeric(18,3),
  "WFS_FEATURE_REF" character varying(35),
  CONSTRAINT "PK_SUMMARY_ALLOCATIONS" PRIMARY KEY ("ORGANIZATION_ID", "REPORT_ID", "REPORT_UNIT_ID", "SUMMARY_SEQ"),
  CONSTRAINT "FK_SUMMARY_ALLOCATION-LU_BENEFICIAL_USE" FOREIGN KEY ("BENEFICIAL_USE_ID")
      REFERENCES "WADE"."LU_BENEFICIAL_USE" ("LU_SEQ_NO") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "FK_SUMMARY_ALLOCATION-LU_FRESH_SALINE_INDICATOR" FOREIGN KEY ("FRESH_SALINE_IND")
      REFERENCES "WADE"."LU_FRESH_SALINE_INDICATOR" ("LU_SEQ_NO") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "FK_SUMMARY_ALLOCATION-LU_SOURCE_TYPE" FOREIGN KEY ("SOURCE_TYPE")
      REFERENCES "WADE"."LU_SOURCE_TYPE" ("LU_SEQ_NO") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "FK_SUMMARY_ALLOCATION-REPORTING_UNIT" FOREIGN KEY ("ORGANIZATION_ID", "REPORT_ID", "REPORT_UNIT_ID")
      REFERENCES "WADE"."REPORTING_UNIT" ("ORGANIZATION_ID", "REPORT_ID", "REPORT_UNIT_ID") MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE "WADE"."SUMMARY_ALLOCATION"
  OWNER TO "WADE";
COMMENT ON TABLE "WADE"."SUMMARY_ALLOCATION"
  IS 'Annual summary of water allocations within the reporting unit.';
COMMENT ON COLUMN "WADE"."SUMMARY_ALLOCATION"."ORGANIZATION_ID" IS 'unique identifier assigned to the organization.';
COMMENT ON COLUMN "WADE"."SUMMARY_ALLOCATION"."REPORT_ID" IS 'A unique identifier assigned to the report by the reporting organization.';
COMMENT ON COLUMN "WADE"."SUMMARY_ALLOCATION"."REPORT_UNIT_ID" IS 'A unique identifier assigned to the reporting unit by the reporting organization.';
COMMENT ON COLUMN "WADE"."SUMMARY_ALLOCATION"."SUMMARY_SEQ" IS 'Unique sequence number for the summary.';
COMMENT ON COLUMN "WADE"."SUMMARY_ALLOCATION"."BENEFICIAL_USE_ID" IS 'Unique identifier for the beneficial use.';


-- Index: "WADE"."FKI_SUMMARY_ALLOCATION-LU_BENEFICIAL_USE"

-- DROP INDEX "WADE"."FKI_SUMMARY_ALLOCATION-LU_BENEFICIAL_USE";

CREATE INDEX "FKI_SUMMARY_ALLOCATION-LU_BENEFICIAL_USE"
  ON "WADE"."SUMMARY_ALLOCATION"
  USING btree
  ("BENEFICIAL_USE_ID");

-- Index: "WADE"."FKI_SUMMARY_ALLOCATION-LU_FRESH_SALINE_INDICATOR"

-- DROP INDEX "WADE"."FKI_SUMMARY_ALLOCATION-LU_FRESH_SALINE_INDICATOR";

CREATE INDEX "FKI_SUMMARY_ALLOCATION-LU_FRESH_SALINE_INDICATOR"
  ON "WADE"."SUMMARY_ALLOCATION"
  USING btree
  ("FRESH_SALINE_IND");

-- Index: "WADE"."FKI_SUMMARY_ALLOCATION-LU_SOURCE_TYPE"

-- DROP INDEX "WADE"."FKI_SUMMARY_ALLOCATION-LU_SOURCE_TYPE";

CREATE INDEX "FKI_SUMMARY_ALLOCATION-LU_SOURCE_TYPE"
  ON "WADE"."SUMMARY_ALLOCATION"
  USING btree
  ("SOURCE_TYPE");

-- Index: "WADE"."FKI_SUMMARY_ALLOCATION-REPORTING_UNIT"

-- DROP INDEX "WADE"."FKI_SUMMARY_ALLOCATION-REPORTING_UNIT";

CREATE INDEX "FKI_SUMMARY_ALLOCATION-REPORTING_UNIT"
  ON "WADE"."SUMMARY_ALLOCATION"
  USING btree
  ("ORGANIZATION_ID" COLLATE pg_catalog."default", "REPORT_ID" COLLATE pg_catalog."default", "REPORT_UNIT_ID" COLLATE pg_catalog."default");

